<?php

/**
 * @file
 * Allows to add a block with the links to various social media platforms.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function social_media_platforms_theme($existing, $type, $theme, $path) {
    return [
        'social_media_platforms_links' => [
            'variables' => [
              'links' => [],
              'attributes' => new Attribute(),
            ],
            'template' => 'social-media-platforms-links',
      ],
    ];
  }


/**
 * Attaching css file.
 */
function social_media_platforms_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'social_media_platforms/social_media_platforms.theme';
}
